// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1B82z0KJLpo4T-ZZP_VTyj2jNS2B_JWM',
    appId: '1:888247091984:web:c1e1baa2bec3e675801b95',
    messagingSenderId: '888247091984',
    projectId: 'siheducation',
    authDomain: 'siheducation.firebaseapp.com',
    storageBucket: 'siheducation.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgHjDohqind6JYBa7OTekGXd3Mrg2Srgs',
    appId: '1:888247091984:android:0e7f19da1dd6e715801b95',
    messagingSenderId: '888247091984',
    projectId: 'siheducation',
    storageBucket: 'siheducation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCobK-40yySRwHWvk_FIPQRZOx_ojSvrz0',
    appId: '1:888247091984:ios:ff4474f44342a95a801b95',
    messagingSenderId: '888247091984',
    projectId: 'siheducation',
    storageBucket: 'siheducation.appspot.com',
    iosBundleId: 'com.example.ruralEducation',
  );
}
